/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 6714.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/6714-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera makeDefault={false} far={1000} near={400000} position={[128.331, 141.896, -41.329]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <PerspectiveCamera makeDefault={false} far={400000} near={1000} fov={25.115} position={[-11.501, 274.673, 194.915]} rotation={[-1.005, -0.014, 0.565]} scale={100} />
      <OrthographicCamera makeDefault={false} far={1000} near={400000} position={[0, 0, 392.563]} rotation={[0, 0, Math.PI / 2]} scale={100} />
      <OrthographicCamera makeDefault={false} far={1000} near={400000} position={[1587.429, 0, 0]} rotation={[0.549, -1.57, -0.423]} scale={100} />
      <mesh geometry={nodes.Frames.geometry} material={materials['Black.jpg']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Display_wall.geometry} material={materials['White.jpg']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Solids.geometry} material={materials['LISBOA-SIX.jpg']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/6714-transformed.glb')
