/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 casa-4.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/casa-4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[1, 0, -1]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[1, 0, -1]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[1, 0, -1]} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[1, 0, -1]} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[1, 0, -1]} />
    </group>
  )
}

useGLTF.preload('/casa-4.glb')
