/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 low-polly-character.glb --transform
Author: YD Visual (https://sketchfab.com/ydvisual)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultra-low-poly-animated-character-mixamo-based-186f3f7ffc30449a9bfce39f647abc92
Title: Ultra Low Poly Animated Character (Mixamo based)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/low-polly-character-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.m_body}
          skeleton={nodes.Object_7.skeleton}
          scale={0.02}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.m_face}
          skeleton={nodes.Object_8.skeleton}
          scale={0.02}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/low-polly-character-transformed.glb");
