/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 6714.glb --transform
*/
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";
import { useEffect } from "react";
import { Mesh, MeshStandardMaterial } from "three";

export function TestSolid(props: GroupProps) {
  const solid = useGLTF("/models/6714-transformed.glb");
  useEffect(() => {
    // Receive Shadows
    solid.scene.traverse((child) => {
      if (
        child instanceof Mesh &&
        child.material instanceof MeshStandardMaterial
      ) {
        child.receiveShadow = true;
      }
    });
  }, [solid]);
  return (
    <RigidBody type="fixed" colliders="trimesh" position={[10, -1.2, 10]}>
      <primitive object={solid.scene} />
    </RigidBody>
  );
}

useGLTF.preload("/6714-transformed.glb");
